---
  # - name: "Playing with Ansible and copy"
  #   hosts: localhost
  #   tasks:
  #   - name: Copy Readme
  #     copy: 
  #       mode: preserve
  #       src: "README.md" 
  #       dest: "READMEcopy.md"
  - name: "making sure stuff installed"
    hosts: cvms
    become: yes
    tasks:
    - name: Install Python3
      yum:
        name: python3